version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env.prod
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4


networks:
  app-network:
    driver: bridge


